### ISSUE TITLE
When I try to play a sound the bot joins and leaves. No sounds

### ISSUE THREAD

**Issue by StoneMoney** [nicholastay/discord-fx#1]
No sound is played.
`[@StoneMoney :: <FIRST> :: #random] ~ FX - !mlg`
from the console.

MP3 file named 1 is located in /fx/mlg/

Running on windows
Help?

**Comment by nicholastay** [comment]
The bot still works for me. Are you sure you have encoded the mp3 file using the `fxe.cmd` (windows) script in the repository using the instructions set out in the `README.md`?

Edit: you can use `fxef.cmd` in the repo by just double clicking it directly and it can do a guided process by simply dragging the source file onto the `.cmd` file then it can convert a file ready for use into the right directory.
