### ISSUE TITLE
Set Volume

### ISSUE THREAD

**Issue by Sikksens** [nicholastay/discord-fx#2]
Is there any way I could lower the default volume of the sounds?

**Comment by nicholastay** [comment]
The way I play sounds in this module is not run through ffmpeg or the discord.js volume transformer to save performance if many people are playing sounds, hence why you need to use `fxe` to encode files beforehand.

The easiest way to lower the volume would probably be to lower the source volume in something like Audacity then encoding it for the bot. Or you could just lower the bot's volume client-side in Discord.

**Comment by Sikksens** [comment]
Ok that makes sense now, thanks!
