### ISSUE TITLE
Bot joins channel, bot won't play any sound.

### ISSUE THREAD

**Issue by ChrCar627** [nicholastay/discord-fx#3]
I set up the bot as per the readme, but whenever I try to run a command (including the already set up !vape), the bot will join the channel, stay for a second or 2, and then just leave without playing a sound.

I also am not able to play the encoded mp3 files with any other program that I tried, although I'm not sure if that is by design or not.

**Comment by nicholastay** [comment]
Although the script is quite old and hasn't been updated for a while, it still seems to work on my end. Have you made sure that `node-opus` is installed correctly and built correctly when running `npm install`?
